apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-health-reporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://github.com/mvs5465-test/local-k8s-apps
    targetRevision: main
    path: manifests/cluster-health-reporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
