apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argocd
spec:
  project: cluster
  sources:
    - repoURL: https://github.com/mvs5465-test/local-k8s-apps
      targetRevision: HEAD
      ref: values

    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 3.8.1
      chart: k8s-monitoring
      helm:
        releaseName: k8s-monitoring
        valueFiles:
          - $values/values/k8s-monitoring/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
