apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: cluster
  sources:
    - repoURL: https://github.com/mvs5465-test/local-k8s-apps
      targetRevision: HEAD
      ref: values

    - repoURL: https://vmware-tanzu.github.io/helm-charts
      targetRevision: 11.4.0
      chart: velero
      helm:
        releaseName: velero
        valueFiles:
          - $values/values/velero/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
