apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-query-router
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://github.com/mvs5465/cluster-query-router
    targetRevision: main
    path: chart
    helm:
      releaseName: cluster-query-router
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
