apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://github.com/mvs5465/cluster-home
    targetRevision: main
    path: chart
    helm:
      releaseName: homepage
      values: |
        image:
          repository: ghcr.io/mvs5465/cluster-home
          tag: main
          pullPolicy: Always

        fullnameOverride: homepage

        service:
          type: ClusterIP
          port: 80
          targetPort: 8080

        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: home.lan
              paths:
                - path: /
                  pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
