apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://helm.otwld.com/
    targetRevision: 1.44.0
    chart: ollama
    helm:
      releaseName: ollama
      values: |
        ollama:
          models:
            pull:
              - phi4-mini

        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 3000m
            memory: 8Gi

        persistentVolume:
          enabled: true
          size: 10Gi

        gpu:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: ai

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
