apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://helm.otwld.com/
    targetRevision: 1.45.0
    chart: ollama
    helm:
      releaseName: ollama
      values: |
        ollama:
          models:
            pull:
              - phi4-mini

        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
          limits:
            cpu: 4000m
            memory: 5Gi

        persistence:
          ollama:
            enabled: true
            type: hostPath
            hostPath: /Users/matthewschwartz/clusterstorage/ollama
            mountPath: /root/.ollama

        gpu:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: ai

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
