alertmanager:
  enabled: false

ruler:
  enabled: false

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    size: 2Gi

querier:
  replicas: 1

query_scheduler:
  replicas: 1

compactor:
  persistentVolume:
    size: 2Gi

store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    size: 2Gi

rollout_operator:
  enabled: false

kafka:
  enabled: false

mimir:
  structuredConfig:
    ingest_storage:
      enabled: false
    ingester:
      push_grpc_method_enabled: true
      ring:
        replication_factor: 1
    store_gateway:
      sharding_ring:
        replication_factor: 1

minio:
  enabled: true
  persistence:
    size: 2Gi

metaMonitoring:
  serviceMonitor:
    enabled: true
