alertmanager:
  enabled: false

ruler:
  enabled: false

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    size: 2Gi

querier:
  replicas: 1

query_scheduler:
  replicas: 1

compactor:
  persistentVolume:
    size: 2Gi

store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    size: 2Gi

rollout_operator:
  enabled: false

kafka:
  enabled: false

minio:
  enabled: true
  persistence:
    size: 2Gi

metaMonitoring:
  serviceMonitor:
    enabled: true
