apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 28.12.0
    chart: prometheus
    helm:
      releaseName: prometheus
      values: |
        server:
          resources:
            requests:
              cpu: 50m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 768Mi
          retention: "7d"
          persistentVolume:
            enabled: true
            size: 2Gi
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.lan
            path: /
            pathType: Prefix
          extraFlags:
            - web.enable-lifecycle
            - web.enable-remote-write-receiver

        serverFiles:
          prometheus.yml:
            rule_files:
              - /etc/config/recording_rules.yml
              - /etc/config/alerting_rules.yml
              - /etc/config/rules
              - /etc/config/alerts

        alertmanager:
          enabled: false

        kube-state-metrics:
          enabled: false

        prometheus-node-exporter:
          enabled: false

        prometheus-pushgateway:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
