---
# Source: argocd-image-updater/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-image-updater
  namespace: "argocd"
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
---
# Source: argocd-image-updater/templates/configmap-sshconfig.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater-ssh-config
  namespace: "argocd"
---
# Source: argocd-image-updater/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater-config
  namespace: "argocd"
data:
  git.commit-message-template: ""
  git.commit-sign-off: "false"
  git.commit-signing-key: ""
  git.commit-signing-method: ""
  git.email: "argocd-image-updater@local"
  git.user: "argocd-image-updater"
  kube.events: "false"
  log.level: "info"
---
# Source: argocd-image-updater/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater
rules:
  - apiGroups:
    - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - argocd-image-updater.argoproj.io
    resources:
      - imageupdaters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - argocd-image-updater.argoproj.io
    resources:
      - imageupdaters/finalizers
    verbs:
      - update
  - apiGroups:
      - argocd-image-updater.argoproj.io
    resources:
      - imageupdaters/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - patch
      - update
      - watch
---
# Source: argocd-image-updater/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-image-updater
subjects:
- kind: ServiceAccount
  name: argocd-image-updater
  namespace: "argocd"
---
# Source: argocd-image-updater/templates/rbac-leader-election.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater-leader-election-role
  namespace: "argocd"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
# Source: argocd-image-updater/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater
  namespace: "argocd"
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
# Source: argocd-image-updater/templates/rbac-leader-election.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater-leader-election-rolebinding
  namespace: "argocd"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater-leader-election-role
subjects:
- kind: ServiceAccount
  name: argocd-image-updater
  namespace: "argocd"
---
# Source: argocd-image-updater/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
  name: argocd-image-updater
  namespace: "argocd"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-image-updater
subjects:
- kind: ServiceAccount
  name: argocd-image-updater
  namespace: "argocd"
---
# Source: argocd-image-updater/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater-controller
  namespace: "argocd"
  labels:
    helm.sh/chart: argocd-image-updater-1.1.1
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: "v1.1.0"
    app.kubernetes.io/managed-by: Helm
    control-plane: argocd-image-updater-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
      app.kubernetes.io/instance: argocd-image-updater
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 066d07d55bb602f225337f8d676d7a7bdd2286008f1dc35f0b26484f45c5d9ff
      labels:
        app.kubernetes.io/name: argocd-image-updater
        app.kubernetes.io/instance: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      securityContext:
        runAsNonRoot: true
      containers:
        - name: argocd-image-updater-controller
          command:
            - /manager
          args:
            - --metrics-bind-address=:8443
            - run
          env:
          - name: ARGOCD_NAMESPACE
            valueFrom:
              configMapKeyRef:
                key: argocd.namespace
                name: argocd-image-updater-config
                optional: true
          - name: IMAGE_UPDATER_INTERVAL
            valueFrom:
              configMapKeyRef:
                key: interval
                name: argocd-image-updater-config
                optional: true
          - name: IMAGE_UPDATER_LOGLEVEL
            valueFrom:
              configMapKeyRef:
                key: log.level
                name: argocd-image-updater-config
                optional: true
          - name: IMAGE_UPDATER_LOGFORMAT
            valueFrom:
              configMapKeyRef:
                key: log.format
                name: argocd-image-updater-config
                optional: true
          - name: MAX_CONCURRENT_APPS
            valueFrom:
              configMapKeyRef:
                key: max_concurrent_apps
                name: argocd-image-updater-config
                optional: true
          - name: MAX_CONCURRENT_RECONCILES
            valueFrom:
              configMapKeyRef:
                key: max_concurrent_reconciles
                name: argocd-image-updater-config
                optional: true
          - name: GIT_COMMIT_USER
            valueFrom:
              configMapKeyRef:
                key: git.user
                name: argocd-image-updater-config
                optional: true
          - name: GIT_COMMIT_EMAIL
            valueFrom:
              configMapKeyRef:
                key: git.email
                name: argocd-image-updater-config
                optional: true
          - name: GIT_COMMIT_SIGNING_KEY
            valueFrom:
              configMapKeyRef:
                key: git.commit-signing-key
                name: argocd-image-updater-config
                optional: true
          - name: GIT_COMMIT_SIGNING_METHOD
            valueFrom:
              configMapKeyRef:
                key: git.commit-signing-method
                name: argocd-image-updater-config
                optional: true
          - name: GIT_COMMIT_SIGN_OFF
            valueFrom:
              configMapKeyRef:
                key: git.commit-sign-off
                name: argocd-image-updater-config
                optional: true
          - name: IMAGE_UPDATER_KUBE_EVENTS
            valueFrom:
              configMapKeyRef:
                key: kube.events
                name: argocd-image-updater-config
                optional: true
          - name: ENABLE_WEBHOOK
            valueFrom:
              configMapKeyRef:
                name: argocd-image-updater-config
                key: webhook.enable
                optional: true
          - name: WEBHOOK_PORT
            valueFrom:
              configMapKeyRef:
                name: argocd-image-updater-config
                key: webhook.port
                optional: true
          - name: QUAY_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: argocd-image-updater-secret
                key: webhook.quay-secret
                optional: true
          - name: DOCKER_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: argocd-image-updater-secret
                key: webhook.docker-secret
                optional: true
          - name: GHCR_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: argocd-image-updater-secret
                key: webhook.ghcr-secret
                optional: true
          - name: HARBOR_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: argocd-image-updater-secret
                key: webhook.harbor-secret
                optional: true
          - name: WEBHOOK_RATELIMIT_ALLOWED
            valueFrom:
              configMapKeyRef:
                name: argocd-image-updater-config
                key: webhook.ratelimit-allowed
                optional: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          image: "quay.io/argoprojlabs/argocd-image-updater:v1.1.0"
          imagePullPolicy: Always
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
            - name: webhook
              containerPort: 8082
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 30
          resources:
            {}
          volumeMounts:
          - mountPath: /app/config
            name: image-updater-conf
          - mountPath: /app/config/ssh
            name: ssh-known-hosts
          - mountPath: /app/.ssh
            name: ssh-config
          - mountPath: /tmp
            name: tmp
          - name: ssh-signing-key
            mountPath: /app/ssh-keys/id_rsa
            readOnly: true
            subPath: sshPrivateKey
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          items:
          - key: registries.conf
            path: registries.conf
          - key: git.commit-message-template
            path: commit.template
          name: argocd-image-updater-config
          optional: true
        name: image-updater-conf
      - configMap:
          name: argocd-ssh-known-hosts-cm
          optional: true
        name: ssh-known-hosts
      - configMap:
          name: argocd-image-updater-ssh-config
          optional: true
        name: ssh-config
      - name: ssh-signing-key
        secret:
          secretName: ssh-git-creds
          optional: true
      - emptyDir: {}
        name: tmp
