apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: services
imagePullSecrets:
- name: ghcr-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: monitoring
imagePullSecrets:
- name: ghcr-secret
