apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-secret
spec:
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - ai
      - argocd
      - services
      - monitoring
      - github-pr-slack-notifier
  refreshTime: 3m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: kubernetes-master-secrets
      kind: ClusterSecretStore
    target:
      name: ghcr-secret
      creationPolicy: Owner
      template:
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: >-
            {"auths":{"ghcr.io":{"username":"mvs5465","password":"{{ .token }}","auth":"{{ list "mvs5465" .token | join ":" | b64enc }}"}}}
    data:
    - secretKey: token
      remoteRef:
        key: ghcr-master-secret
        property: token
