apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: github-pr-slack-notifier-secret
spec:
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - github-pr-slack-notifier
  refreshTime: 3m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: kubernetes-master-secrets
      kind: ClusterSecretStore
    target:
      name: github-pr-slack-notifier-secret
      creationPolicy: Owner
    data:
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: github-pr-slack-notifier-master-secret
        property: github_app_private_key
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: github-pr-slack-notifier-master-secret
        property: slack_bot_token
