apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: grafana-alerting-secret
spec:
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - monitoring
  refreshTime: 3m
  externalSecretSpec:
    refreshInterval: 3m
    secretStoreRef:
      name: kubernetes-master-secrets
      kind: ClusterSecretStore
    target:
      name: grafana-alerting-secret
      creationPolicy: Owner
    data:
    - secretKey: GRAFANA_ALERTS_SLACK_WEBHOOK_URL
      remoteRef:
        key: grafana-alerting-master-secret
        property: slack_webhook_url
