apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: openclaw-secret
spec:
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - ai
  refreshTime: 3m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: kubernetes-master-secrets
      kind: ClusterSecretStore
    target:
      name: openclaw-secrets
      creationPolicy: Owner
    data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: openclaw-master-secret
        property: gateway_token
