apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: snapreview-secret
spec:
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - services
  refreshTime: 3m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: kubernetes-master-secrets
      kind: ClusterSecretStore
    target:
      name: snapreview-secret
      creationPolicy: Owner
    data:
    - secretKey: client_secret
      remoteRef:
        key: snapreview-master-secret
        property: GITHUB_CLIENT_SECRET
    - secretKey: session_secret
      remoteRef:
        key: snapreview-master-secret
        property: SESSION_SECRET
    - secretKey: redis_url
      remoteRef:
        key: snapreview-master-secret
        property: REDIS_URL
