apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: minio-root-credentials
spec:
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - backups
  refreshTime: 3m
  externalSecretSpec:
    refreshInterval: 3m
    secretStoreRef:
      name: kubernetes-master-secrets
      kind: ClusterSecretStore
    target:
      name: minio-root-credentials
      creationPolicy: Owner
    data:
    - secretKey: rootUser
      remoteRef:
        key: velero-minio-master-secret
        property: root_user
    - secretKey: rootPassword
      remoteRef:
        key: velero-minio-master-secret
        property: root_password
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: velero-credentials
spec:
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - velero
  refreshTime: 3m
  externalSecretSpec:
    refreshInterval: 3m
    secretStoreRef:
      name: kubernetes-master-secrets
      kind: ClusterSecretStore
    target:
      name: velero-credentials
      creationPolicy: Owner
      template:
        type: Opaque
        engineVersion: v2
        data:
          cloud: |
            [default]
            aws_access_key_id={{ .access_key_id }}
            aws_secret_access_key={{ .secret_access_key }}
    data:
    - secretKey: access_key_id
      remoteRef:
        key: velero-minio-master-secret
        property: access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: velero-minio-master-secret
        property: secret_access_key
