apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-storage-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /Users/matthewschwartz/clusterstorage/velero
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: backups
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: minio-storage-pv
  resources:
    requests:
      storage: 100Gi
