cluster:
  name: local-k3s

destinations:
  - name: mimir
    type: prometheus
    url: http://mimir-gateway.monitoring.svc.cluster.local/api/v1/push
  - name: prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
  - name: loki
    type: loki
    url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  - name: tempo
    type: otlp
    protocol: grpc
    url: tempo.monitoring.svc.cluster.local:4317
    tls:
      insecure: true
    metrics:
      enabled: false
    logs:
      enabled: false

clusterMetrics:
  enabled: true

clusterEvents:
  enabled: true

podLogs:
  enabled: true
  extraDiscoveryRules: |
    rule {
      source_labels = ["namespace", "pod"]
      separator = "/"
      regex = "monitoring/(loki-0|k8s-monitoring-alloy-.*)"
      action = "drop"
    }

applicationObservability:
  enabled: true
  destinations:
    - mimir
    - loki
    - tempo
  receivers:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

annotationAutodiscovery:
  enabled: true

prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true

integrations:
  enabled: true
  loki:
    instances:
      - name: loki
        namespaces:
          - monitoring
        logs:
          enabled: false
  mimir:
    instances:
      - name: mimir
        namespaces:
          - monitoring
        logs:
          enabled: false
  tempo:
    instances:
      - name: tempo
        namespaces:
          - monitoring
        metrics:
          portName: prom-metrics
        logs:
          enabled: false

alloy-metrics:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

alloy-singleton:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 20m
        memory: 48Mi
      limits:
        cpu: 150m
        memory: 128Mi

alloy-receiver:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        cpu: 200m
        memory: 192Mi

alloy-logs:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 192Mi

extraObjects:
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: argocd-application-controller-metrics
      namespace: argocd
    spec:
      jobLabel: app.kubernetes.io/component
      namespaceSelector:
        matchNames:
          - argocd
      selector:
        matchLabels:
          app.kubernetes.io/instance: argocd
          app.kubernetes.io/name: argocd-metrics
          app.kubernetes.io/component: application-controller
      endpoints:
        - port: http-metrics

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: argocd-applicationset-controller-metrics
      namespace: argocd
    spec:
      jobLabel: app.kubernetes.io/component
      namespaceSelector:
        matchNames:
          - argocd
      selector:
        matchLabels:
          app.kubernetes.io/instance: argocd
          app.kubernetes.io/name: argocd-metrics
          app.kubernetes.io/component: applicationset-controller
      endpoints:
        - port: http-metrics

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: argocd-repo-server-metrics
      namespace: argocd
    spec:
      jobLabel: app.kubernetes.io/component
      namespaceSelector:
        matchNames:
          - argocd
      selector:
        matchLabels:
          app.kubernetes.io/instance: argocd
          app.kubernetes.io/name: argocd-repo-server-metrics
          app.kubernetes.io/component: repo-server
      endpoints:
        - port: http-metrics

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: argocd-server-metrics
      namespace: argocd
    spec:
      jobLabel: app.kubernetes.io/component
      namespaceSelector:
        matchNames:
          - argocd
      selector:
        matchLabels:
          app.kubernetes.io/instance: argocd
          app.kubernetes.io/name: argocd-server-metrics
          app.kubernetes.io/component: server
      endpoints:
        - port: http-metrics
